[project]
name = "licita-tracker-sibal"

[nixpacks]
pnpm_version = "8.15.1"
pnpm_install_args = "--frozen-lockfile"  # Usamos versão fixa do pnpm para garantir compatibilidade

[variables]              # Variáveis globais (opcional)
GROQ_MODEL   = "meta-llama/llama-4-scout-17b-16e-instruct"

### Serviço 1 – MCP Server ###########################################
[[services]]
name          = "mcp-server"
root          = "packages/mcp-server"
builder       = "nixpacks"          # usa node 18 por padrão
pre_build     = "npm install -g pnpm@8.15.1 && pnpm install --frozen-lockfile"
buildCommand  = "pnpm run build"
startCommand  = "node dist/index.js"
internal_port = 8080

  [services.variables]
  API_KEY      = "local-dev"        # defina no painel
  GROQ_API_KEY = "gsk_xxx"

  [services.http_checks]
  path      = "/health"
  interval  = "10s"
  timeout   = "5s"
  grace_period = "5s"

### Serviço 2 – Frontend #############################################
[[services]]
name          = "frontend"
root          = "."
builder       = "nixpacks"
pre_build     = "npm install -g pnpm@8.15.1 && pnpm install --frozen-lockfile"
buildCommand  = "pnpm run build"
startCommand  = "pnpm run preview -- --port $PORT --host 0.0.0.0"
internal_port = "$PORT"             # deixa Railway escolher

  [services.variables]
  VITE_MCP_URL    = "https://{{ .services.mcp-server.domain }}/mcp"
  VITE_MCP_HEADER = "api-key"
  VITE_MCP_TOKEN  = "local-dev"
  VITE_LOVABLE_MODEL = "${GROQ_MODEL}"

  [services.http_checks]
  path = "/"
