
services:
  # Backend MCP Server
  - type: web
    name: mcp-server
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm install && cd src/backend && npx tsc
    startCommand: cd src/backend && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health

  # Frontend React
  - type: web
    name: frontend
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_MCP_URL
        fromService:
          type: web
          name: mcp-server
          property: host
