name: CI

on:
  push:
    branches: [windsufcode]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm -r --filter ./... run build

      # Deploy automático pelo Render Blueprint
      # Não é mais necessário fazer deploy manual via GitHub Actions
